"""add_agent_id_to_chat_messages

Revision ID: 1917035a67b3
Revises: 4009c0fed1cf
Create Date: 2025-05-05 16:12:04.070774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1917035a67b3'
down_revision = '4009c0fed1cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_messages_agent_id'), 'chat_messages', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_agent_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'agent_id')
    # ### end Alembic commands ### 