"""add_tool_call_fields_to_chat_messages

Revision ID: 26d9be805451
Revises: 4220219587ae
Create Date: 2025-05-25 23:19:20.256837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26d9be805451'
down_revision = '4220219587ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_calls_agent_id', table_name='tool_calls')
    op.drop_index('ix_tool_calls_conversation_id', table_name='tool_calls')
    op.drop_index('ix_tool_calls_id', table_name='tool_calls')
    op.drop_index('ix_tool_calls_is_deleted', table_name='tool_calls')
    op.drop_index('ix_tool_calls_tool_call_id', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.add_column('chat_messages', sa.Column('tool_calls', sa.JSON(), nullable=True))
    op.add_column('chat_messages', sa.Column('tool_call_id', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('tool_name', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('tool_status', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('tool_result', sa.JSON(), nullable=True))
    op.add_column('chat_messages', sa.Column('tool_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'tool_error')
    op.drop_column('chat_messages', 'tool_result')
    op.drop_column('chat_messages', 'tool_status')
    op.drop_column('chat_messages', 'tool_name')
    op.drop_column('chat_messages', 'tool_call_id')
    op.drop_column('chat_messages', 'tool_calls')
    op.create_table('tool_calls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tool_call_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('function_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('arguments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='tool_calls_agent_id_fkey'),
    sa.ForeignKeyConstraint(['conversation_id'], ['sessions.id'], name='tool_calls_conversation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tool_calls_pkey')
    )
    op.create_index('ix_tool_calls_tool_call_id', 'tool_calls', ['tool_call_id'], unique=False)
    op.create_index('ix_tool_calls_is_deleted', 'tool_calls', ['is_deleted'], unique=False)
    op.create_index('ix_tool_calls_id', 'tool_calls', ['id'], unique=False)
    op.create_index('ix_tool_calls_conversation_id', 'tool_calls', ['conversation_id'], unique=False)
    op.create_index('ix_tool_calls_agent_id', 'tool_calls', ['agent_id'], unique=False)
    # ### end Alembic commands ### 