"""Create user_models table with all fields

Revision ID: 3cbeed4cb881
Revises: 8d0861179d36
Create Date: 2025-06-01 19:56:55.032603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbeed4cb881'
down_revision = '8d0861179d36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 