"""add_tools_enabled_field_to_agent

Revision ID: 4220219587ae
Revises: 5860bbe65382
Create Date: 2025-05-07 21:36:45.883743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4220219587ae'
down_revision = '5860bbe65382'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 