"""remove_unique_constraint_from_note_session_id

Revision ID: 499f78cca3f7
Revises: dc9dfdbeaa28
Create Date: 2025-05-06 19:36:01.829835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499f78cca3f7'
down_revision = 'dc9dfdbeaa28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_session_id', table_name='notes')
    op.create_index(op.f('ix_notes_session_id'), 'notes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_session_id'), table_name='notes')
    op.create_index('ix_notes_session_id', 'notes', ['session_id'], unique=True)
    # ### end Alembic commands ### 