"""add_agent_tools

Revision ID: 5860bbe65382
Revises: 499f78cca3f7
Create Date: 2025-05-07 19:26:22.555977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5860bbe65382'
down_revision = '499f78cca3f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('tools_enabled', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'tools_enabled')
    # ### end Alembic commands ### 