"""sync_tool_call_history_model_with_database

Revision ID: 726a6247d8bc
Revises: 4f6d10a3c4c6
Create Date: 2025-06-04 10:38:15.170201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726a6247d8bc'
down_revision = '4f6d10a3c4c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['session_id'], ['id'])
    
    # 先添加可空的session_id列
    op.add_column('tool_call_history', sa.Column('session_id', sa.Integer(), nullable=True))
    
    # 从conversation_id复制数据到session_id
    op.execute("UPDATE tool_call_history SET session_id = conversation_id")
    
    # 现在设置为NOT NULL
    op.alter_column('tool_call_history', 'session_id', nullable=False)
    
    op.create_index(op.f('ix_tool_call_history_session_id'), 'tool_call_history', ['session_id'], unique=False)
    op.create_foreign_key(None, 'tool_call_history', 'sessions', ['session_id'], ['id'])
    op.drop_column('tool_call_history', 'conversation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_call_history', sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # 从session_id复制数据到conversation_id
    op.execute("UPDATE tool_call_history SET conversation_id = session_id")
    
    op.drop_constraint(None, 'tool_call_history', type_='foreignkey')
    op.drop_index(op.f('ix_tool_call_history_session_id'), table_name='tool_call_history')
    op.drop_column('tool_call_history', 'session_id')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ### 