"""remove_name_avatar_url_is_public_from_agent

Revision ID: 75736769d677
Revises: c01b20da9700
Create Date: 2025-06-03 15:52:27.841223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75736769d677'
down_revision = 'c01b20da9700'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_agent', 'agents', type_='unique')
    op.drop_index('ix_agents_user_id', table_name='agents')
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_agent_not_deleted', 'agents', ['user_id', 'is_deleted'])
    op.drop_column('agents', 'name')
    op.drop_column('agents', 'is_public')
    op.drop_column('agents', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('agents', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_agent_not_deleted', 'agents', type_='unique')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.create_index('ix_agents_user_id', 'agents', ['user_id'], unique=True)
    op.create_unique_constraint('uq_user_agent', 'agents', ['user_id'])
    # ### end Alembic commands ### 