"""Add user_models table

Revision ID: 8d0861179d36
Revises: 34e3b499a835
Create Date: 2025-06-01 19:56:38.230307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0861179d36'
down_revision = '34e3b499a835'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 