"""add_token_fields_to_chat_message

Revision ID: 954037d7f08f
Revises: 55fc46e14f8c
Create Date: 2025-05-03 17:54:02.175899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954037d7f08f'
down_revision = '55fc46e14f8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'total_tokens')
    op.drop_column('chat_messages', 'prompt_tokens')
    # ### end Alembic commands ### 