"""add_agent_table_and_relations

Revision ID: a7f88327a512
Revises: 0901960e95e1
Create Date: 2025-05-04 06:56:07.299943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f88327a512'
down_revision = '0901960e95e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 