"""rename_chat_id_to_conversation_id

Revision ID: f385d374b006
Revises: c4a5055badaf
Create Date: 2025-05-03 00:34:46.032762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f385d374b006'
down_revision = 'c4a5055badaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加新列
    op.add_column('chat_messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    
    # 复制数据
    op.execute("UPDATE chat_messages SET conversation_id = chat_id")
    
    # 添加外键约束和索引之前，设置新列为非空
    op.alter_column('chat_messages', 'conversation_id', nullable=False)
    
    # 创建索引
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    
    # 添加外键约束
    op.create_foreign_key(None, 'chat_messages', 'chats', ['conversation_id'], ['id'])
    
    # 删除旧的外键约束
    op.drop_constraint('chat_messages_chat_id_fkey', 'chat_messages', type_='foreignkey')
    
    # 删除旧索引
    op.drop_index('ix_chat_messages_chat_id', table_name='chat_messages')
    
    # 最后删除旧列
    op.drop_column('chat_messages', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加旧列
    op.add_column('chat_messages', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # 复制数据
    op.execute("UPDATE chat_messages SET chat_id = conversation_id")
    
    # 设置旧列为非空
    op.alter_column('chat_messages', 'chat_id', nullable=False)
    
    # 创建旧索引
    op.create_index('ix_chat_messages_chat_id', 'chat_messages', ['chat_id'], unique=False)
    
    # 添加旧的外键约束
    op.create_foreign_key('chat_messages_chat_id_fkey', 'chat_messages', 'chats', ['chat_id'], ['id'])
    
    # 删除新的外键约束
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    
    # 删除新索引
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    
    # 最后删除新列
    op.drop_column('chat_messages', 'conversation_id')
    # ### end Alembic commands ### 